# Generated by Django 2.2.7 on 2019-12-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.CharField(default='abc', max_length=500),
            preserve_default=False,
        ),
    ]
